name: Deploy Web App to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F20E4D19FE724C33B44074A747CD3B4D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4EE28C2B731344AFABC89AA0AA2AF38D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_980B940B7C3149168399F13DB2FD0D6B }}
      
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: npm install and build
        run: |
          cd webapp
          npm install
          cd ..
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pa4-24030009'
          slot-name: 'Production'
          package: ./webapp
